/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhoneNumber = IDL.Text;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'date' : IDL.Int,
  'presentStudents' : IDL.Vec(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'teacher' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'phoneNumber' : PhoneNumber,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'parentPhone' : PhoneNumber,
  'classId' : IDL.Nat,
});
export const Class = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'teacher' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([IDL.Nat, IDL.Text, PhoneNumber], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createClass' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAttendance' : IDL.Func(
      [IDL.Nat, IDL.Int],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClassStudents' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getStudentAttendanceHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getTeacherClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'takeAttendance' : IDL.Func([IDL.Nat, IDL.Int, IDL.Vec(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhoneNumber = IDL.Text;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'date' : IDL.Int,
    'presentStudents' : IDL.Vec(IDL.Nat),
  });
  const UserRole = IDL.Variant({ 'teacher' : IDL.Null, 'parent' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'phoneNumber' : PhoneNumber,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'parentPhone' : PhoneNumber,
    'classId' : IDL.Nat,
  });
  const Class = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'teacher' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([IDL.Nat, IDL.Text, PhoneNumber], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createClass' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAttendance' : IDL.Func(
        [IDL.Nat, IDL.Int],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClassStudents' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getMyStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getStudentAttendanceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getTeacherClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'takeAttendance' : IDL.Func([IDL.Nat, IDL.Int, IDL.Vec(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };